### ISSUE TITLE
Filling in letters

### ISSUE THREAD

**Issue by henryiii** [lhcb/glossary#12]
We should have at least one entry per letter. Remaining letters:

- [x] A
- [x] B
- [x] F
- [x] J
- [x] K
- [x] O
- [x] Q
- [x] R
- [x] U
- [x] Y
- [x] Z

If a letter does not get an entry, links to it should be removed eventually. I think we can fill out all letters, though, it's a challenge. :)

**Comment by eduardo-rodrigues** [comment]
Thanks for the list. I would not go as far as removing the entries empty for now. It's not a professional glossary and in any case I don't think anybody will be confused by empty entries ;-).

**Comment by henryiii** [comment]
I just mean eventually, when we broadcast this more generally. It doesn't look good if someone opens up the glossary, clicks on A, then gets nothing.

**Comment by eduardo-rodrigues** [comment]
There are a few letters to tick off with the PRs from today. We are getting there ...

**Comment by eduardo-rodrigues** [comment]
Done now with PR https://github.com/lhcb/glossary/pull/22/.
