### ISSUE TITLE
Why not single page?

### ISSUE THREAD

**Issue by rmatev** [lhcb/glossary#19]
Single page seems much simpler (with a TOC in front if you like). I know I can use the search box on the left, but why not just Cmd/Ctrl+F

**Comment by eduardo-rodrigues** [comment]
You mean a single page in what is served at https://lhcb.github.io/glossary/?

Is it so strange to click on the first letter of what you want and then do a little scroll?

The TOC is already there. As for the search box at the left-top, that's really neat if you want to look for all entries related to a topic, say grid, dirac, etc.

As the glossary grows, having a single and gigantic page makes little sense to me.

**Comment by rmatev** [comment]
Yes.

The "per letter" organisation seems weird and arbitrary to me.

The search box is inferior to ctrl+f, it does not support neither fuzzy nor partial match. At least the latter works with ctrl+f (e.g. try searching for "keeping")

I'm not sure how gigantic it will be. Googling for similar stuff I see examples of both ways. Here are some single page examples
https://public-archive.web.cern.ch/public-archive/en/Science/Glossary-en.php http://cms.web.cern.ch/content/glossary
https://atlas.cern/glossary
https://earth.esa.int/web/guest/glossary

**Comment by henryiii** [comment]
Let’s keep the current source file organization as it is. However, if we would like to present a single page, that is fairly easy to do, I believe.  Another option that Mike Sokoloff mentioned, we could provide a page that summarizes all of the terms, only without the definitions. Again, I believe these can be written as preprocessing steps in the CI.

**Comment by rmatev** [comment]
thanks @henryiii looks much nicer than the list of letters :) Feel free to close the issue
