### ISSUE TITLE
New term suggestions (detector hardware)

### ISSUE THREAD

**Issue by chrisburr** [lhcb/glossary#34]
After seeing `ASIC` mentioned, I think it would be nice to add some more hardware terms. To dump a few suggestions:

- [x] ASIC
- [ ] FPGA
- [x] GBTx
- [x] CLARO
- [x] VeloPix
- [x] Timepix
- [ ] SPIDR
- [x] MaPMT
- [x] HPD
- [x] PCIe40
- [x] SOL40
- [x] TELL40
- [x] SODIN
- [x] DAQ
- [x] MiniDAQ
- [ ] VFB
- [ ] OPB
- [ ] DC/DC
- [ ] BXID/BCID
- [x] TFC
- [ ] Telescope

**Comment by eduardo-rodrigues** [comment]
Thanks @chrisburr. Will you ping 1-2 of the electronics/DAQ people to try and help?

**Comment by chrisburr** [comment]
There is a workshop/hackathon thing at the moment but I'll pester them next week.

**Comment by seadanda** [comment]
I'll add a few upgrade-related terms tomorrow when I'm back in the office. Some of those suggested + more.

**Comment by eduardo-rodrigues** [comment]
Hi @seadanda, getting back to this after 2 weeks: do you want to try and create a PR addressing the suggestions above?

**Comment by seadanda** [comment]
Hi @eduardo-rodrigues, sorry yea I got back to the office and have been snowed under ever since. I have a deadline for changes to a paper today so as of next week I'll have some time.

**Comment by eduardo-rodrigues** [comment]
Next week sounds good. Good luck with the paper ...

**Comment by seadanda** [comment]
Brain dump while it's on my mind:
- [ ] PCIe40
- [ ] SOL40
- [ ] TELL40
- [ ] SODIN
- [ ] DAQ
- [ ] MiniDAQ
- [ ] VFB
- [ ] OPB
- [ ] DC/DC
- [ ] BXID/BCID
- [ ] TFC
- [ ] Telescope

**Comment by eduardo-rodrigues** [comment]
Kind ping, @seadanda.

**Comment by eduardo-rodrigues** [comment]
@seadanda, do you still mean to add these definitions in the glossary?

**Comment by eduardo-rodrigues** [comment]
I copied all lists of entries to the top comment so that the list of tasks reflects the definitions to provide.

**Comment by eduardo-rodrigues** [comment]
The remaining words suggested don't seem that useful or extremely rare, and nobody looked for them, clearly. I have no idea what SPIDR means for example, in LHCb, never came across it in almost 20 years ,-). Closing.
