### ISSUE TITLE
New term suggestions

### ISSUE THREAD

**Issue by chrisburr** [lhcb/glossary#36]
The following list of terms should be defined:

- [x] BPV (Best Primary Vertex)
- [ ] VD (Vertex Displacement)
- [ ] VDCHI2
- [x] IP (Impact Parameter)
- [x] IPCHI2
- [x] FD (Flight Distance)
- [x] FDCHI2
- [ ] Prescale
- [ ] Postscale
- [x] RTA

I don't have time to add them at the moment but I noticed they're missing.

**Comment by eduardo-rodrigues** [comment]
*RTA* should also be added.

**Comment by eduardo-rodrigues** [comment]
You cannot just click on the tick boxes and get the list updated? I actually edited the entry. Fine now :-).

**Comment by eduardo-rodrigues** [comment]
Closing since there seems to be no appetite for this. We can always add on these variables if somebody discusses them and asks for them here.
