### ISSUE TITLE
link not properly resolved

### ISSUE THREAD

**Issue by closier** [lhcb/glossary#39]
if i opened the page https://lhcb.github.io/glossary/glossary/D.html and I want to try to access the DavInci project website , it does not work as the link https://lhcb.github.io/glossary/glossary/lhcbdoc.web.cern.ch/lhcbdoc/davinci does not exist. the proper link is http://lhcbdoc.web.cern.ch/lhcbdoc/davinci/
And it would be good to open a NEW tab when you click on a link which is outside the gitbook .

**Comment by eduardo-rodrigues** [comment]
To me all external links open a new tab. Maybe an issue with your browser settings?
