### ISSUE TITLE
New term suggestions (simulation)

### ISSUE THREAD

**Issue by admorris** [lhcb/glossary#44]
The following list of terms should be defined:

- [x] Event type
- [x] DecFile
- [x] Fast simulation
  - [x] ReDecay
  - [x] Tracker-only
  - [x] RICHless
  - [x] Parametric and/or Delphes
  - [ ] SplitSim
- [ ] Generator (maybe "Event generator")
  - [ ] Generator-level and/or MC truth
  - [ ] Generator cut ("GenCut")
  - [ ] Generator efficiency
- [ ] HepMC
- [ ] Filtered MC

**Comment by eduardo-rodrigues** [comment]
@abmorris, a PR form today reminds me that several updates are outstanding, such as this one. Would this be something you are willing to tackle soon-ish? Maybe ask Dominik for help?

**Comment by abmorris** [comment]
Thanks for reminding me about this. I have appealed for help in the Simulation Mattermost channel and I'll take a look when I have some free time

**Comment by eduardo-rodrigues** [comment]
Many thanks! Indeed the glossary **is** a community effort ...

**Comment by lukascalle** [comment]
Event type, DecFile, Fast simulation, ReDecay, Tracker-only, RICHless, Delphes are added in https://github.com/lhcb/glossary/pull/49.

**Comment by eduardo-rodrigues** [comment]
Hi @adamdddave, would you be so kind to discuss with Michal and Gloria to try and add the missing terms above to our LHCb glossary? That would be appreciated. Advance thanks,

**Comment by eduardo-rodrigues** [comment]
Closing since there seems to be no appetite for this. We can always add on these names if somebody discusses them and asks for them here.
