### ISSUE TITLE
Add distributed analysis words

### ISSUE THREAD

**Issue by egede** [lhcb/glossary#6]
So here is a list of possible distributed analysis words to add

- [ ] Application
- [x] Certificate
- [ ] Dataset
- [ ] Distributed analysis
- [x] Ganga
- [x] Grid proxy
- [ ] Job
- [x] LFN
- [ ] Merger
- [ ] Monitoring
- [x] PFN
- [ ] Proxy
- [x] SE: Storage Element
- [x] Site
- [ ] Splitter
- [x] Tier
- [x] VO: Virtual organisation
- [ ] Worker node

**Comment by egede** [comment]
Just in the explanation or also in the terms themselves, like `Job (Ganga)`?

**Comment by eduardo-rodrigues** [comment]
In the explanations is probably natural in many cases. Others such as you example make more sense, since a job is a general thing too.

**Comment by mesmith75** [comment]
Do we really want to get into individual Ganga things here?

**Comment by eduardo-rodrigues** [comment]
Nope. But the example of "Job" is a clear example where an entry only makes sense for Ganga.

**Comment by egede** [comment]
> Do we really want to get into individual Ganga things here?

I could not quite decide. I think it makes sense to include the words that are used in general discussion but things like `Merger` are probably beyond what is required.

**Comment by eduardo-rodrigues** [comment]
So these items can now all be ticked off, @mesmith75 ?

**Comment by mesmith75** [comment]
I missed a few that looked too ganga specific (job, application, monitoring, splitter, merger, dataset) and I left out tier because I cannot remember the definitions off the top of my head. But otherwise yes.

I can't tick it myself as I'm not a developer on this repository.

**Comment by chrisburr** [comment]
I've invited you to the LHCb organisation.

**Comment by henryiii** [comment]
Note: you can see all entries with `git grep '##'`.

**Comment by eduardo-rodrigues** [comment]
@mesmith75, will you add some more entries before we close this? To me, Certificate and Tier are the general and interesting entries to have (others may be too Ganga specific).

**Comment by mesmith75** [comment]
@eduardo-rodrigues Sure I'll add a few more. I have put in Grid Certificate which I think should suffice.

**Comment by mesmith75** [comment]
I think this can be closed now.

**Comment by eduardo-rodrigues** [comment]
Thank you both.
